### ISSUE TITLE
Unable to start WMS and Web UI from 1.0_M1 and M2 due to NPE

### ISSUE THREAD

**Issue by zawor** [geoserver/geoserver-cloud#95] opened 2021-08-23 17:16 UTC
When hitting `docker-compose --compatibility up -d` I get very same exception under WMS and Web UI... same applies to 1.0 M1 and M2. Both when built from source and fetched from docker hub. Did minor digging in the code and it seems like `WMSInfo` service cannot be resolved by underlying `GeoServer` from catalog. But it was simple run through stack trace with not a lot insight from my side.

What do I miss? 

PS: If more input required simple let me know

the infamous exception:

> wms_1        | 2021-08-23 16:37:12.353 ERROR 17 --- [           main] o.s.boot.SpringApplication               : Application run failed
wms_1        | 
wms_1        | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getMapKvpReader' defined in URL [jar:file:/opt/app/wms-service.jar!/BOOT-INF/lib/gs-wms-2.19.0.jar!/applicationContext.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.wms.map.GetMapKvpRequestReader]: Constructor threw exception; nested exception is java.lang.NullPointerException
wms_1        | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:313) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:294) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1203) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
wms_1        | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
wms_1        | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
wms_1        | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
wms_1        | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
wms_1        | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
wms_1        | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
wms_1        | 	at org.geoserver.cloud.wms.WmsApplication.main(WmsApplication.java:21) ~[classes!/:na]
wms_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
wms_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
wms_1        | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
wms_1        | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
wms_1        | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[wms-service.jar:na]
wms_1        | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[wms-service.jar:na]
wms_1        | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[wms-service.jar:na]
wms_1        | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[wms-service.jar:na]
wms_1        | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.wms.map.GetMapKvpRequestReader]: Constructor threw exception; nested exception is java.lang.NullPointerException
wms_1        | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:309) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	... 28 common frames omitted
wms_1        | Caused by: java.lang.NullPointerException: null
wms_1        | 	at org.geoserver.wms.map.GetMapKvpRequestReader.getTimeoutMillis(GetMapKvpRequestReader.java:177) ~[gs-wms-2.19.0.jar!/:2.19.0]
wms_1        | 	at org.geoserver.wms.map.GetMapKvpRequestReader.<init>(GetMapKvpRequestReader.java:140) ~[gs-wms-2.19.0.jar!/:2.19.0]
wms_1        | 	at org.geoserver.wms.map.GetMapKvpRequestReader.<init>(GetMapKvpRequestReader.java:131) ~[gs-wms-2.19.0.jar!/:2.19.0]
wms_1        | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
wms_1        | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
wms_1        | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
wms_1        | 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
wms_1        | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
wms_1        | 	... 30 common frames omitted
wms_1        | 
wms_1        | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getMapKvpReader' defined in URL [jar:file:/opt/app/wms-service.jar!/BOOT-INF/lib/gs-wms-2.19.0.jar!/applicationContext.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.wms.map.GetMapKvpRequestReader]: Constructor threw exception; nested exception is java.lang.NullPointerException
wms_1        | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:313)
wms_1        | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:294)
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356)
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1203)
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
wms_1        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
wms_1        | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
wms_1        | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
wms_1        | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
wms_1        | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
wms_1        | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
wms_1        | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
wms_1        | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
wms_1        | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
wms_1        | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
wms_1        | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
wms_1        | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
wms_1        | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
wms_1        | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
wms_1        | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
wms_1        | 	at org.geoserver.cloud.wms.WmsApplication.main(WmsApplication.java:21)
wms_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
wms_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
wms_1        | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
wms_1        | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
wms_1        | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
wms_1        | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
wms_1        | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
wms_1        | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
wms_1        | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.wms.map.GetMapKvpRequestReader]: Constructor threw exception; nested exception is java.lang.NullPointerException
wms_1        | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217)
wms_1        | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
wms_1        | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:309)
wms_1        | 	... 28 more
wms_1        | Caused by: java.lang.NullPointerException
wms_1        | 	at org.geoserver.wms.map.GetMapKvpRequestReader.getTimeoutMillis(GetMapKvpRequestReader.java:177)
wms_1        | 	at org.geoserver.wms.map.GetMapKvpRequestReader.<init>(GetMapKvpRequestReader.java:140)
wms_1        | 	at org.geoserver.wms.map.GetMapKvpRequestReader.<init>(GetMapKvpRequestReader.java:131)
wms_1        | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
wms_1        | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
wms_1        | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
wms_1        | 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
wms_1        | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
wms_1        | 	... 30 more
wms_1        | 2021/08/23 16:37:12 Command exited with error: exit status 255

**Comment by groldan** [comment] 2021-10-03 18:33
Hey @zawor, that was most probably caused by some geoserver startup race conditions that were fixed for 1.0-RC1.

Please try 1.0-RC1 out and let us know if the problem persists.
Here are two `docker-compose.yml` files you can try out right away:

* [shared data directory set up](http://geoserver.org/geoserver-cloud/deploy/docker-compose/stable/shared_datadir/docker-compose.yml)
* [shared PostgreSQL jdbcconfig set up](http://geoserver.org/geoserver-cloud/deploy/docker-compose/stable/jdbcconfig/docker-compose.yml)

**Comment by groldan** [comment] 2021-12-19 00:00
Closing as fixed by the startup race condition patch

**Closed by groldan** 2021-12-19 00:00 UTC
