### ISSUE TITLE
com.microsoft.rest.v2.http.NettyClient   :  a header value contains prohibited character 0x20 at index 0.

### ISSUE THREAD

**Issue by Muks1m** [geoserver/geoserver-cloud#296] opened 2023-01-10 08:29 UTC
Hello team, I am getting this error while deploying the 0.0.46  snapshot version.

Here is the complete log

2023-01-10 03:01:18.695  WARN 1 --- [ntLoopGroup-1-2] com.microsoft.rest.v2.http.NettyClient   : Error emitted on channel c8203510. Message: a header value contains prohibited character 0x20 at index 0.
2023-01-10 03:01:18.709 ERROR 1 --- [ntLoopGroup-1-2] c.m.azure.storage.blob.LoggingFactory    : Unexpected failure attempting to make request.
Error message:'a header value contains prohibited character 0x20 at index 0.'

2023-01-10 03:01:18.709 ERROR 1 --- [ntLoopGroup-1-2] c.m.azure.storage.blob.LoggingFactory    : Unexpected failure attempting to make request.
Error message:'a header value contains prohibited character 0x20 at index 0.'

2023-01-10 03:01:18.715  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryCacheController': Unsatisfied dependency expressed through field 'broker'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcStorageBroker' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Cannot resolve reference to bean 'gwcConfigBlobStore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcConfigBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Cannot resolve reference to bean 'gwcBlobStore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geowebcache.storage.CompositeBlobStore]: Constructor threw exception; nested exception is org.geowebcache.storage.StorageException: Failed to setup Azure connection and container
2023-01-10 03:01:18.728  WARN 1 --- [           main] i.m.c.instrument.internal.DefaultGauge   : Failed to apply the value function for the gauge 'geoserver.config.update_sequence'. Note that subsequent logs will be logged at debug level.

java.lang.NullPointerException: Cannot invoke "org.geoserver.config.GeoServerInfo.getUpdateSequence()" because the return value of "org.geoserver.config.GeoServer.getGlobal()" is null
	at org.geoserver.cloud.autoconfigure.metrics.catalog.CatalogMetrics.lambda$registerObservedUpdateSequence$0(CatalogMetrics.java:74) ~[gs-cloud-catalog-backend-common-1.0-SNAPSHOT.jar:na]
	at io.micrometer.core.instrument.Gauge.lambda$builder$0(Gauge.java:58) ~[micrometer-core-1.8.12.jar:1.8.12]
	at io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble(StrongReferenceGaugeFunction.java:48) ~[micrometer-core-1.8.12.jar:1.8.12]
	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:53) ~[micrometer-core-1.8.12.jar:1.8.12]
	at io.opentelemetry.javaagent.instrumentation.micrometer.AzureMonitorMeterRegistry.trackGauge(AzureMonitorMeterRegistry.java:76) ~[na:na]
	at io.opentelemetry.javaagent.instrumentation.micrometer.AzureMonitorMeterRegistry.publish(AzureMonitorMeterRegistry.java:51) ~[na:na]
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:54) ~[micrometer-core-1.8.12.jar:1.8.12]
	at io.micrometer.core.instrument.push.PushMeterRegistry.close(PushMeterRegistry.java:96) ~[micrometer-core-1.8.12.jar:1.8.12]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.Collections$SetFromMap.forEach(Unknown Source) ~[na:na]
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.close(CompositeMeterRegistry.java:239) ~[micrometer-core-1.8.12.jar:1.8.12]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:319) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:596) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.geoserver.cloud.gwc.app.GeoWebCacheApplication.main(GeoWebCacheApplication.java:15) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[bin/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[bin/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[bin/:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[bin/:na]

2023-01-10 03:01:19.131 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryCacheController': Unsatisfied dependency expressed through field 'broker'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcStorageBroker' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Cannot resolve reference to bean 'gwcConfigBlobStore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcConfigBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Cannot resolve reference to bean 'gwcBlobStore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geowebcache.storage.CompositeBlobStore]: Constructor threw exception; nested exception is org.geowebcache.storage.StorageException: Failed to setup Azure connection and container
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.geoserver.cloud.gwc.app.GeoWebCacheApplication.main(GeoWebCacheApplication.java:15) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[bin/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[bin/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[bin/:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[bin/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcStorageBroker' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Cannot resolve reference to bean 'gwcConfigBlobStore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcConfigBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Cannot resolve reference to bean 'gwcBlobStore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geowebcache.storage.CompositeBlobStore]: Constructor threw exception; nested exception is org.geowebcache.storage.StorageException: Failed to setup Azure connection and container
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:707) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.3.24.jar:5.3.24]
	... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcConfigBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Cannot resolve reference to bean 'gwcBlobStore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geowebcache.storage.CompositeBlobStore]: Constructor threw exception; nested exception is org.geowebcache.storage.StorageException: Failed to setup Azure connection and container
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:707) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[spring-beans-5.3.24.jar:5.3.24]
	... 43 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcBlobStore' defined in URL [jar:file:/opt/app/bin/BOOT-INF/lib/gs-gwc-2.21.0-CLOUD.jar!/geowebcache-core-context.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geowebcache.storage.CompositeBlobStore]: Constructor threw exception; nested exception is org.geowebcache.storage.StorageException: Failed to setup Azure connection and container
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[spring-beans-5.3.24.jar:5.3.24]
	... 55 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geowebcache.storage.CompositeBlobStore]: Constructor threw exception; nested exception is org.geowebcache.storage.StorageException: Failed to setup Azure connection and container
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.24.jar:5.3.24]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.24.jar:5.3.24]
	... 65 common frames omitted
Caused by: org.geowebcache.storage.StorageException: Failed to setup Azure connection and container
	at org.geowebcache.azure.AzureClient.<init>(AzureClient.java:112) ~[gwc-azure-blob-1.21.0.jar:1.21.x/f53b7f0a4a56d99bebe0af69ca58caf7a221d347]
	at org.geowebcache.azure.AzureBlobStore.<init>(AzureBlobStore.java:77) ~[gwc-azure-blob-1.21.0.jar:1.21.x/f53b7f0a4a56d99bebe0af69ca58caf7a221d347]
	at org.geowebcache.azure.AzureBlobStoreInfo.createInstance(AzureBlobStoreInfo.java:235) ~[gwc-azure-blob-1.21.0.jar:1.21.x/f53b7f0a4a56d99bebe0af69ca58caf7a221d347]
	at org.geowebcache.storage.CompositeBlobStore.loadBlobStore(CompositeBlobStore.java:431) ~[gwc-core-1.21.0.jar:1.21.x/f53b7f0a4a56d99bebe0af69ca58caf7a221d347]
	at org.geowebcache.storage.CompositeBlobStore.loadBlobStores(CompositeBlobStore.java:372) ~[gwc-core-1.21.0.jar:1.21.x/f53b7f0a4a56d99bebe0af69ca58caf7a221d347]
	at org.geowebcache.storage.CompositeBlobStore.<init>(CompositeBlobStore.java:153) ~[gwc-core-1.21.0.jar:1.21.x/f53b7f0a4a56d99bebe0af69ca58caf7a221d347]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.24.jar:5.3.24]
	... 67 common frames omitted
Caused by: java.lang.IllegalArgumentException: a header value contains prohibited character 0x20 at index 0.
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueValidator.validate(DefaultHttpHeaders.java:395) ~[netty-codec-http-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueValidator.validate(DefaultHttpHeaders.java:387) ~[netty-codec-http-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.handler.codec.DefaultHeaders.validateValue(DefaultHeaders.java:1012) ~[netty-codec-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.handler.codec.DefaultHeaders.add(DefaultHeaders.java:330) ~[netty-codec-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:364) ~[netty-codec-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:115) ~[netty-codec-http-4.1.85.Final.jar:4.1.85.Final]
	at com.microsoft.rest.v2.http.NettyClient.createDefaultHttpRequest(NettyClient.java:605) ~[client-runtime-2.1.0.jar:na]
	at com.microsoft.rest.v2.http.NettyClient.access$400(NettyClient.java:64) ~[client-runtime-2.1.0.jar:na]
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete(NettyClient.java:275) ~[client-runtime-2.1.0.jar:na]
	at io.opentelemetry.javaagent.instrumentation.netty.common.FutureListenerWrappers$WrappedFutureListener.operationComplete(FutureListenerWrappers.java:106) ~[na:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2023-01-10T03:01:19.133084460Z

**Comment by groldan** [comment] 2023-04-28 15:07
okay, this seems like a duplicate of #325. I'm working on it. Closing this one as a duplicate.

**Closed by groldan** 2023-04-28 15:07 UTC
