### ISSUE TITLE
GWC configuration changes  done in the UI are not propagated correctly

### ISSUE THREAD

**Issue by AlexGacon** [geoserver/geoserver-cloud#310] opened 2023-03-16 13:04 UTC
After changing the configuration of an existing S3 blobstore to point another bucket, we must restart the GWC pods to have the configuration updated on GWC side.

If not, the previous configuration is used by the pod.

**Comment by AlexGacon** [comment] 2023-03-16 13:14
Update : all changes done on GWC configuration are not propagated to GWC pod. I created a new gridset and it was not visible through the GWC REST API.

**Comment by groldan** [comment] 2023-11-29 13:00
Closing as can't reproduce.
If you have more insights with a current gscloud version feel free to re-open.

**Closed by groldan** 2023-11-29 13:00 UTC
Labels: Not a bug
