### ISSUE TITLE
REST service HTML response fails

### ISSUE THREAD

**Issue by MaYohann** [geoserver/geoserver-cloud#113] opened 2021-10-28 07:33 UTC
Hi!

When running the [composition](http://geoserver.org/geoserver-cloud/deploy/docker-compose/stable/shared_datadir/docker-compose.yml) with version RC1 as mentionned [here](https://github.com/geoserver/geoserver-cloud/issues/106#issuecomment-946884088)

Some REST services failed on GET /. The HTTP Status is 200, but the content is an error.

Seems to be impacted:
- layergroups
- layers
- namespaces
- styles
- workspaces

For example:
GET: http://localhost:9090/rest/workspaces/

Resut in:

	Workspace "FreeMarker template error (DEBUG mode; use RETHROW in production!):
	The following has evaluated to null or missing:
	==> properties [in template "WorkspaceInfo.ftl" at line 2, column 14]

	----
	Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either
	specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing
	</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis:
	(myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
	----

	----
	FTL stack trace ("~" means nesting-related):
	- Failed at: ${properties.name} [in template "WorkspaceInfo.ftl" at line 2, column 12]
	----

	Java stack trace (for programmers):
	----
	freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85)
	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48)
		at freemarker.core.NonHashException.<init>(NonHashException.java:49)
			at freemarker.core.Dot._eval(Dot.java:48)
			at freemarker.core.Expression.eval(Expression.java:101)
			at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
			at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
			at freemarker.core.Environment.visit(Environment.java:334)
			at freemarker.core.Environment.visit(Environment.java:340)
			at freemarker.core.Environment.process(Environment.java:313)
			at freemarker.template.Template.process(Template.java:383)
			at
			org.geoserver.rest.converters.FreemarkerHTMLMessageConverter.writeInternal(FreemarkerHTMLMessageConverter.java:98)
			at
			org.geoserver.rest.converters.FreemarkerHTMLMessageConverter.writeInternal(FreemarkerHTMLMessageConverter.java:35)
			at
			org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
			at
			org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290)
			at
			org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:181)
			at
			org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
			at
			org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:123)
			at
			org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
			at
			org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
			at
			org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
			at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
			at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
			at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
			at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
			at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
			at
			org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
			at
			org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
			at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
			at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
			at
			org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
			at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
			at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
			at
			org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:53)
			at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
			at
			org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204)
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
			at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
			at
			org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
			at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
			at
			org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
			at
			org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
			at
			org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
			at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
			at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
			at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
			at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
			at
			org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73)
			at org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48)
			at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
			at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:158)
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at
			org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
			at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
			at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
			at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
			at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
			at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
			at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
			at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
			at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
			at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
			at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
			at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
			at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
			at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
			at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
			at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
			at java.base/java.lang.Thread.run(Thread.java:829)
			Template processing error The following has evaluated to null or missing:
			==> properties [in template "WorkspaceInfo.ftl" at line 2, column 14]

			----
			Tip: If the failing expression is known to legally refer to something that's sometimes null or missing,
			either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>
					when-missing</#if>. (These only cover the last step of the expression; to cover the whole
			expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
			----

			----
			FTL stack trace ("~" means nesting-related):
			- Failed at: ${properties.name} [in template "WorkspaceInfo.ftl" at line 2, column 12]
			----

**Comment by groldan** [comment] 2021-12-01 04:11
Hello, sorry for the late reply. I think that's related to some obscure or rather antique ways inside geoserver to determine the current request's path (i.e. to discriminate the servlet context like in `/geoserver` from the path like in `/rest/bla`). 
Can you confirm this happens only when asking for an HTML response?

**Comment by groldan** [comment] 2022-12-26 12:32
Duplicate of #247

**Comment by groldan** [comment] 2023-11-27 02:27
FreeMarker templates are working the same as on upstream (vanilla) GeoServer, where the same error happens on empty collections (e.g. an empty namespace).
If interested, file a bug on https://osgeo-org.atlassian.net/jira/software/c/projects/GEOS/issues/
Closing as won't fix since it's not a GeoServer Cloud issue.

**Closed by groldan** 2023-11-27 02:27 UTC
Labels: bug, duplicate, wontfix
