### ISSUE TITLE
The wps service failed to start using idea

### ISSUE THREAD

**Issue by MissingLoves** [geoserver/geoserver-cloud#408] opened 2024-01-04 09:27 UTC
Hello author：  
       When I was in the WPS services FilteringXmlBeanDefinitionReader class again to find the jar package applicationContext. XML configuration, the error of the project， Illegal character in opaque part at index 12: jar:file:/C:\Users\hui\AppData\Local\Temp\classpath1532823373.jar!/
<img width="927" alt="微信图片_20240104172533" src="https://github.com/geoserver/geoserver-cloud/assets/67035022/620d9944-c567-4a51-aa70-ee5e1857ab3b">
     Is there any idea construction and development process

**Comment by groldan** [comment] 2024-01-29 04:06
Closing as duplicate of #415

**Closed by groldan** 2024-01-29 04:06 UTC
Labels: duplicate
